seed = 10
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/microsoft"
num_policy = "noisy-quantile"

[optimizer]
type = "ALSO"
lr = 4.4272307818789154e-05
pi_lr = 0.00011972458853342605
weight_decay = 0.00029342776891140213
pi_decay = 0.0013063893012676532

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 896
dropout = 0.43312155235056815

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 92
d_embedding = 28
frequency_init_scale = 0.027674181457522377
lite = false
