seed = 13
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/maps-routing"
cat_policy = "ordinal"

[optimizer]
type = "ALSO"
lr = 0.0002492918708273529
pi_lr = 0.0004644688386081937
weight_decay = 0.000332907013327805
pi_decay = 0.002279629199408707

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 928
dropout = 0.013229270077465688

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 44
d_embedding = 24
frequency_init_scale = 0.14633027338321883
lite = false
