seed = 6
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/microsoft"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 5.1446283124264676e-05
weight_decay = 0.0
loss = "dro"
loss_penalty = "kl"
loss_shift_cost = 0.19406441746979106
loss_ndraws = 0.0017786927271515826

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.46164253185310017

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 60
d_embedding = 20
frequency_init_scale = 0.02016955754970435
lite = false
