seed = 4
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/churn"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
loss = "importance"
loss_tau = 0.3529265865765047
lr = 0.000300361026267116
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 400
dropout = 0.18751259009918475

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 48
d_embedding = 24
frequency_init_scale = 0.12139944977879316
lite = false
