seed = 14
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/delivery-eta"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
loss = "importance"
loss_tau = 0.0033201652532993953
lr = 9.142256875166606e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 640
dropout = 0.0

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 76
d_embedding = 28
frequency_init_scale = 0.014324904662321569
lite = false
