seed = 1
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/black-friday"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00022613913840024302
weight_decay = 0.0
loss = "static_weights"

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 944
dropout = 0.3928412946657055

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 40
d_embedding = 16
frequency_init_scale = 1.0199541622070023
lite = false
