seed = 3
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/ecom-offers"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
loss = "importance"
loss_tau = 0.8399892579364729
lr = 0.00016458529135281383
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 224
dropout = 0.2890640002401304

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 52
d_embedding = 16
frequency_init_scale = 0.019359658341994268
lite = false
